<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Config\" />
    <Folder Include="Formatter\" />
    <Folder Include="Framework\Alarm\Logger\" />
    <Folder Include="Framework\Device\Card\" />
    <Folder Include="Framework\Machine\" />
    <Folder Include="Framework\Motion\" />
    <Folder Include="Framework\Plc\" />
    <Folder Include="Framework\Station\" />
    <Folder Include="Framework\Task\" />
    <Folder Include="Leisai\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Core">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Core.dll</HintPath>
    </Reference>
    <Reference Include="Framework">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Framework.dll</HintPath>
    </Reference>
    <Reference Include="Interfaces">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="MaterialDesignThemes.Wpf">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\MaterialDesignThemes.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\MainApp\bin\Debug\net5.0-windows\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="NLog">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\NLog.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
