// <auto-generated>
// 此文件由 Roslyn Source Generator 自动生成，请勿手动修改！
// 修改 LogMessageDefinitions.cs 后重新编译即可更新此文件
// 
// ⚠️ 当前为手动生成版本（Generator 环境调试中）
// 后续 Generator 正常工作后将自动替换此文件
// </auto-generated>

using System;
using System.Globalization;

namespace Core.Logging
{
    public static partial class LogMessages
    {
        #region 运动控制相关 (Motion Control)

        /// <summary>
        /// 获取 AxisMovedToTarget 的本地化日志消息
        /// </summary>
        public static string AxisMovedToTarget(object arg0, object arg1, object arg2)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            // 优先使用 LocalizationService 动态获取（支持运行时切换）
            try
            {
                var localized = Localization.GetResource("Log_AxisMovedToTarget");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0, arg1, arg2);
                }
            }
            catch { }

            // 回退到硬编码翻译（保证即使 LocalizationService 不可用也能工作）
            return culture switch
            {
                "zh-CN" => string.Format("轴 {0} 已移动到目标位置 ({1:F3}, {2:F3})", arg0, arg1, arg2),
                "en-US" => string.Format("Axis {0} moved to target position ({1:F3}, {2:F3})", arg0, arg1, arg2),
                _ => $"轴 {0} 已移动到目标位置 ({1:F3}, {2:F3})"
            };
        }

        /// <summary>
        /// 获取 AxisHomingDone 的本地化日志消息
        /// </summary>
        public static string AxisHomingDone(object arg0)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_AxisHomingDone");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("轴 {0} 回零完成", arg0),
                "en-US" => string.Format("Axis {0} homing completed", arg0),
                _ => $"轴 {0} 回零完成"
            };
        }

        /// <summary>
        /// 获取 EmergencyStopTriggered 的本地化日志消息
        /// </summary>
        public static string EmergencyStopTriggered(object arg0)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_EmergencyStopTriggered");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("收到急停信号，正在停止轴 {0}", arg0),
                "en-US" => string.Format("Emergency stop received, stopping axis {0}", arg0),
                _ => $"收到急停信号，正在停止轴 {0}"
            };
        }

        #endregion

        #region IO 控制相关 (I/O Control)

        /// <summary>
        /// 获取 DiStatusChanged 的本地化日志消息
        /// </summary>
        public static string DiStatusChanged(object arg0, object arg1)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_DiStatusChanged");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0, arg1);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("DI [{0}] 状态: {1}", arg0, arg1),
                "en-US" => string.Format("DI [{0}] status: {1}", arg0, arg1),
                _ => $"DI [{0}] 状态: {1}"
            };
        }

        /// <summary>
        /// 获取 DoToggled 的本地化日志消息
        /// </summary>
        public static string DoToggled(object arg0, object arg1)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_DoToggled");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0, arg1);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("DO [{0}] 已切换为 {1}", arg0, arg1),
                "en-US" => string.Format("DO [{0}] toggled to {1}", arg0, arg1),
                _ => $"DO [{0}] 已切换为 {1}"
            };
        }

        /// <summary>
        /// 获取 DoToggleFailed 的本地化日志消息
        /// </summary>
        public static string DoToggleFailed(object arg0, object arg1)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_DoToggleFailed");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0, arg1);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("DO [{0}] 切换失败: {1}", arg0, arg1),
                "en-US" => string.Format("DO [{0}] toggle failed: {1}", arg0, arg1),
                _ => $"DO [{0}] 切换失败: {1}"
            };
        }

        #endregion

        #region 流程控制相关 (Process Control)

        /// <summary>
        /// 获取 ProcessStarted 的本地化日志消息
        /// </summary>
        public static string ProcessStarted(object arg0)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_ProcessStarted");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("流程开始: {0}", arg0),
                "en-US" => string.Format("Process started: {0}", arg0),
                _ => $"流程开始: {0}"
            };
        }

        /// <summary>
        /// 获取 StepCompleted 的本地化日志消息
        /// </summary>
        public static string StepCompleted(object arg0, object arg1)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_StepCompleted");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0, arg1);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("步骤 [{0}] {1} 完成", arg0, arg1),
                "en-US" => string.Format("Step [{0}] {1} completed", arg0, arg1),
                _ => $"步骤 [{0}] {1} 完成"
            };
        }

        /// <summary>
        /// 获取 ProcessCompleted 的本地化日志消息
        /// </summary>
        public static string ProcessCompleted(object arg0, object arg1)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_ProcessCompleted");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0, arg1);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("流程 {0} 执行完毕，耗时 {1}", arg0, arg1),
                "en-US" => string.Format("Process {0} completed, duration {1}", arg0, arg1),
                _ => $"流程 {0} 执行完毕，耗时 {1}"
            };
        }

        #endregion

        #region 视觉检测相关 (Vision)

        /// <summary>
        /// 获取 CameraTriggered 的本地化日志消息
        /// </summary>
        public static string CameraTriggered(object arg0)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_CameraTriggered");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("触发相机 {0} 拍照", arg0),
                "en-US" => string.Format("Trigger camera {0} capture", arg0),
                _ => $"触发相机 {0} 拍照"
            };
        }

        /// <summary>
        /// 获取 VisionDataReceived 的本地化日志消息
        /// </summary>
        public static string VisionDataReceived(object arg0, object arg1)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_VisionDataReceived");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0, arg1);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("收到相机 {0} 数据: {1} 个测量值", arg0, arg1),
                "en-US" => string.Format("Received camera {0} data: {1} measurements", arg0, arg1),
                _ => $"收到相机 {0} 数据: {1} 个测量值"
            };
        }

        #endregion

        #region 报警系统相关 (Alarm)

        /// <summary>
        /// 获取 AlarmTriggered 的本地化日志消息
        /// </summary>
        public static string AlarmTriggered(object arg0, object arg1)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_AlarmTriggered");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0, arg1);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("报警触发: [{0}] {1}", arg0, arg1),
                "en-US" => string.Format("Alarm triggered: [{0}] {1}", arg0, arg1),
                _ => $"报警触发: [{0}] {1}"
            };
        }

        /// <summary>
        /// 获取 AlarmAcknowledged 的本地化日志消息
        /// </summary>
        public static string AlarmAcknowledged(object arg0)
        {
            EnsureInitialized();
            
            var culture = CultureInfo.CurrentUICulture.Name;

            try
            {
                var localized = Localization.GetResource("Log_AlarmAcknowledged");
                if (!localized.StartsWith("["))
                {
                    return string.Format(localized, arg0);
                }
            }
            catch { }

            return culture switch
            {
                "zh-CN" => string.Format("报警已确认: {0}", arg0),
                "en-US" => string.Format("Alarm acknowledged: {0}", arg0),
                _ => $"报警已确认: {0}"
            };
        }

        #endregion
    }
}
