<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework\Framework.csproj" />
    <ProjectReference Include="..\RecipeManagement\Recipe.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CHSMS">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\CHSMS.dll</HintPath>
    </Reference>
    <Reference Include="Interfaces">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="NLog">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\NLog.dll</HintPath>
    </Reference>
    <Reference Include="Prism">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Prism.dll</HintPath>
    </Reference>
    <Reference Include="SmarterMotion">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\SmarterMotion.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
