// <auto-generated />
using System;
using Interfaces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MainApp.Migrations
{
    [DbContext(typeof(AlarmDbContext))]
    partial class AlarmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Interfaces.PersistentAlarm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("OriginalRawTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasPrecision(4)
                        .HasColumnType("datetime2(4)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Level");

                    b.HasIndex("StationId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Timestamp", "Id")
                        .IsDescending(false, true);

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("Timestamp", "Id"), 90);

                    b.HasIndex("Timestamp", "Level");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Timestamp", "Level"), new[] { "StationId", "Code" });

                    b.ToTable("Alarms");
                });
#pragma warning restore 612, 618
        }
    }
}
