<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0-windows7.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<AssemblyName>ModuleCore</AssemblyName>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Extension\**" />
	  <EmbeddedResource Remove="Extension\**" />
	  <None Remove="Extension\**" />
	  <Page Remove="Extension\**" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="Images\alter.png" />
		<None Remove="Images\button.png" />
		<None Remove="Images\Device1.png" />
		<None Remove="Images\Home, homepage, menu.png" />
		<None Remove="Images\success.png" />
		<None Remove="UserControls\full_screen.png" />
		<None Remove="UserControls\ICON\ashbin.png" />
		<None Remove="UserControls\ICON\full.png" />
		<None Remove="UserControls\ICON\rect.png" />
		<None Remove="UserControls\ICON\rotaterect.png" />
		<None Remove="UserControls\ICON\square.png" />
		<None Remove="UserControls\resources\full.jpg" />
		<None Remove="Views\YIJIMINI.png" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="HandyControl" Version="3.5.1" />
		<PackageReference Include="LiveCharts.Wpf.Core" Version="0.9.8" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="NLog" Version="4.7.12" />
		<PackageReference Include="Prism.Wpf" Version="8.1.97" />
		<PackageReference Include="SkiaSharp" Version="3.119.2" />
		<PackageReference Include="SkiaSharp.NativeAssets.NanoServer" Version="3.119.2" />
		<PackageReference Include="System.Management" Version="6.0.0" />
		<PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
		<PackageReference Include="MaterialDesignColors" Version="5.3.2" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\AlarmModule\AlarmModule.csproj" />
	  <ProjectReference Include="..\Framework\Framework.csproj" />
	  <ProjectReference Include="..\LanguageModule\Language.csproj" />
	  <ProjectReference Include="..\MotionControl\MotionControl.csproj" />
	  <ProjectReference Include="..\RecipeManagement\Recipe.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Core\Core.csproj" />
	  <ProjectReference Include="..\LogViewer\LogViewer.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Images\alter.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Images\Device1.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Images\Home, homepage, menu.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Images\success.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Images\button.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
		<Resource Include="UserControls\ICON\ashbin.png" />
		<Resource Include="UserControls\ICON\full.png" />
		<Resource Include="UserControls\ICON\rect.png" />
		<Resource Include="UserControls\ICON\rotaterect.png" />
		<Resource Include="Views\YIJIMINI.png" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Images\yiji.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="NLog.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Services\" />
	</ItemGroup>
</Project>