<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Task2.cs~RF2b0ed8a.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Core">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Core.dll</HintPath>
    </Reference>
    <Reference Include="Framework">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Framework.dll</HintPath>
    </Reference>
    <Reference Include="halcondotnet">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\halcondotnet.dll</HintPath>
    </Reference>
    <Reference Include="HSMS">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\HSMS.dll</HintPath>
    </Reference>
    <Reference Include="Interfaces">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="NLog">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\NLog.dll</HintPath>
    </Reference>
    <Reference Include="Recipe">
      <HintPath>..\RecipeManagement\bin\Debug\net9.0-windows\Recipe.dll</HintPath>
    </Reference>
    <Reference Include="SmarterMotion">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\SmarterMotion.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
