<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Core">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Core.dll</HintPath>
    </Reference>
    <Reference Include="Prism">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Prism.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
