<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="EFCore.BulkExtensions" Version="8.0.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
	  <PackageReference Include="Prism.Wpf" Version="8.1.97" />
	  <PackageReference Include="System.IO.Ports" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Core">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\Core.dll</HintPath>
    </Reference>
    <Reference Include="NLog">
      <HintPath>..\MainApp\bin\Debug\net9.0-windows7.0\NLog.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
