using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

[Generator]
public class LogMessagesGenerator : ISourceGenerator
{
    public void Execute(GeneratorExecutionContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"=== Generator Execute Called ===");
        sb.AppendLine($"SyntaxReceiver: {context.SyntaxReceiver?.GetType().Name ?? "NULL"}");
        
        var receiver = (LogMessageSyntaxReceiver)context.SyntaxReceiver;
        sb.AppendLine($"CandidateClass: {receiver?.CandidateClass?.Identifier.ValueText ?? "NULL"}");
        
        var definitionsClass = FindLogMessageDefinitionsClass(context);
        sb.AppendLine($"DefinitionsClass: {definitionsClass?.Identifier.ValueText ?? "NULL"}");
        
        context.AddSource("Debug.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));

        if (definitionsClass == null) return;

        var translations = ExtractAllTranslations(definitionsClass);

        if (translations.IsEmpty) return;

        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated>");
        sourceBuilder.AppendLine("// 此文件由 Roslyn Source Generator 自动生成，请勿手动修改！");
        sourceBuilder.AppendLine("// 修改 LogMessageDefinitions.cs 后重新编译即可更新此文件");
        sourceBuilder.AppendLine("// </auto-generated>");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("using System;");
        sourceBuilder.AppendLine("using System.Globalization;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("namespace Core.Logging");
        sourceBuilder.AppendLine("{");
        sourceBuilder.AppendLine("    public static partial class LogMessages");
        sourceBuilder.AppendLine("    {");

        foreach (var translation in translations)
        {
            GenerateMethod(sourceBuilder, translation);
        }

        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine("}");

        context.AddSource("LogMessages.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new LogMessageSyntaxReceiver());
    }

    private ClassDeclarationSyntax FindLogMessageDefinitionsClass(GeneratorExecutionContext context)
    {
        var receiver = (LogMessageSyntaxReceiver)context.SyntaxReceiver;

        if (receiver?.CandidateClass == null) return null;

        var model = context.Compilation.GetSemanticModel(receiver.CandidateClass.SyntaxTree);

        var symbol = model.GetDeclaredSymbol(receiver.CandidateClass);

        return symbol != null && symbol.Name == "LogMessageDefinitions" ? receiver.CandidateClass : null;
    }

    private ImmutableList<(string Name, Dictionary<string, string> Translations, ImmutableArray<IParameterSymbol> Parameters)> 
        ExtractAllTranslations(ClassDeclarationSyntax classDecl)
    {
        var result = ImmutableList.CreateBuilder<(string Name, Dictionary<string, string> Translations, ImmutableArray<IParameterSymbol> Parameters)>();

        var members = classDecl.Members.OfType<FieldDeclarationSyntax>()
            .Where(f => f.Modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword)) &&
                        f.Declaration.Variables.Any(v => v.Initializer != null));

        foreach (var field in members)
        {
            var variable = field.Declaration.Variables.First();
            var name = variable.Identifier.ValueText;
            var attributes = field.AttributeLists
                .SelectMany(al => al.Attributes)
                .Where(a => a.Name.ToString().Contains("LogMessage"));

            var translations = new Dictionary<string, string>();
            
            foreach (var attr in attributes)
            {
                if (attr.ArgumentList.Arguments.Count >= 2)
                {
                    var cultureCode = attr.ArgumentList.Arguments[0].Expression.ToString().Trim('"');
                    var message = attr.ArgumentList.Arguments[1].Expression.ToString().Trim('"');
                    translations[cultureCode] = message;
                }
            }

            if (translations.Count > 0)
            {
                result.Add((name, translations, ImmutableArray<IParameterSymbol>.Empty));
            }
        }

        return result.ToImmutable();
    }

    private void GenerateMethod(StringBuilder builder, (string Name, Dictionary<string, string> Translations, ImmutableArray<IParameterSymbol> Parameters) translation)
    {
        builder.AppendLine($"        /// <summary>");
        builder.AppendLine($"        /// 获取 {translation.Name} 的本地化日志消息");
        builder.AppendLine($"        /// </summary>");

        var firstTranslation = translation.Translations.FirstOrDefault().Value ?? "";
        var paramCount = CountParameters(firstTranslation);

        var parameters = GenerateParameterList(paramCount);
        var paramNames = GenerateParameterNamesList(paramCount);

        builder.AppendLine($"        public static string {translation.Name}({parameters})");
        builder.AppendLine("        {");
        builder.AppendLine("            EnsureInitialized();");
        builder.AppendLine($"            var culture = CultureInfo.CurrentUICulture.Name;");
        builder.AppendLine();

        if (translation.Translations.Any())
        {
            builder.AppendLine("            try");
            builder.AppendLine("            {");
            builder.AppendFormat(
                "                var localized = Localization.GetResource(\"Log_{0}\");\n",
                translation.Name);
            builder.AppendLine("                if (!localized.StartsWith(\"[\"))");
            builder.AppendLine("                {");
            builder.AppendFormat(
                "                    return string.Format(localized, {0});\n",
                paramNames);
            builder.AppendLine("                }");
            builder.AppendLine("            }");
            builder.AppendLine("            catch { }");
            builder.AppendLine();

            builder.AppendLine("            return culture switch");
            builder.AppendLine("            {");

            foreach (var trans in translation.Translations)
            {
                var escapedMsg = EscapeString(trans.Value);
                builder.AppendFormat(
                    "                \"{0}\" => string.Format(\"{1}\", {2}),\n",
                    trans.Key,
                    escapedMsg,
                    paramNames);
            }

            var defaultMsg = EscapeString(translation.Translations.FirstOrDefault().Value ?? "");
            builder.AppendLine($"                _ => $\"{defaultMsg}\"");
            builder.AppendLine("            };");
        }

        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private int CountParameters(string formatString)
    {
        if (string.IsNullOrEmpty(formatString)) return 0;
        
        int maxParam = -1;
        int pos = 0;
        
        while ((pos = formatString.IndexOf('{', pos)) != -1)
        {
            if (pos + 1 < formatString.Length && formatString[pos + 1] != '{')
            {
                var endPos = formatString.IndexOf('}', pos);
                if (endPos > pos)
                {
                    var numStr = formatString.Substring(pos + 1, endPos - pos - 1).Split(':')[0];
                    if (int.TryParse(numStr, out int num))
                    {
                        maxParam = Math.Max(maxParam, num);
                    }
                }
            }
            pos++;
        }
        
        return maxParam + 1;
    }

    private string GenerateParameterList(int count)
    {
        if (count <= 0) return string.Empty;

        var sb = new StringBuilder();
        for (int i = 0; i < count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.AppendFormat("object arg{0}", i);
        }
        return sb.ToString();
    }

    private string GenerateParameterNamesList(int count)
    {
        if (count <= 0) return string.Empty;

        var sb = new StringBuilder();
        for (int i = 0; i < count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.AppendFormat("arg{0}", i);
        }
        return sb.ToString();
    }

    private string EscapeString(string message)
    {
        if (string.IsNullOrEmpty(message)) return string.Empty;
        return message.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}

internal class LogMessageSyntaxReceiver : ISyntaxReceiver
{
    public ClassDeclarationSyntax CandidateClass { get; private set; }

    public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
    {
        if (syntaxNode is ClassDeclarationSyntax classDecl &&
            classDecl.Identifier.ValueText == "LogMessageDefinitions")
        {
            var hasAttribute = classDecl.AttributeLists
                .SelectMany(al => al.Attributes)
                .Any(a => a.Name.ToString().Contains("GenerateLogMessages"));

            if (hasAttribute)
            {
                CandidateClass = classDecl;
            }
        }
    }
}
