using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

[Generator]
public class TestGenerator : ISourceGenerator
{
    public void Execute(GeneratorExecutionContext context)
    {
        var source = "// Generated by TestGenerator at " + System.DateTime.Now.ToString("O");
        context.AddSource("TestGenerated.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    public void Initialize(GeneratorInitializationContext context)
    {
    }
}
